---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

kind: pipeline
type: docker
name: default

steps:
  - name: reuse
    image: fsfe/reuse

  # Create translations for markdown via PO files
  - name: po4a
    image: alpine
    commands:
      - apk add --no-cache diffutils perl-yaml-tiny po4a
      - po4a po4a.conf

  # Create .status file for important i18n translation strings
  - name: check_translations
    image: python:alpine
    commands:
      - python3 check_translations.py site/i18n

  # Build hugo
  - name: hugo
    image: plugins/hugo
    settings:
      source: site
      hugo_version: 0.125.4
      validate: false

  # Build and deploy Docker
  - name: deploy
    image: docker:28
    environment:
      # Environment variables necessary for rootless Docker
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      # Use BuildKit to skip "development" step in Dockerfiles
      DOCKER_BUILDKIT: 1
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    commands:
      - docker ps && echo "tampered with"
      - docker compose down
      - docker compose pull --ignore-buildable --include-deps
      - docker compose -p reuse-website up --build -d
    when:
      branch:
        - main
      event:
        - push
        - tag
        - deployment

node:
  cont2: noris

volumes:
  # Define Docker socket of rootless docker user
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: 52bde5966518aed71528009ae9d2a7a31044f973ad6565148125b4e2a135426c

...
