version = 1

[[annotations]]
path = "site/static/*.schema.json"
precedence = "override"
SPDX-FileCopyrightText = "2025 Free Software Foundation Europe <https://fsfe.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "site/static/fonts/roboto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Google"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "site/static/fonts/fontawesome/css/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Font Awesome <https://fontawesome.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "site/static/fonts/fontawesome/webfonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Font Awesome <https://fontawesome.com>"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "site/static/fonts/fontawesome/webfonts/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "Font Awesome <https://fontawesome.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "site/static/img/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "site/static/img/**.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "site/i18n/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "site/po/**.po**"
precedence = "override"
SPDX-FileCopyrightText = "REUSE contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
